### ISSUE TITLE
请问这个TenhouClient可以用吗?

### ISSUE THREAD

**Issue by ycdoit** [zhangjk95/Tenhou-Client#1]
请问您有用这个Client在Tenhou上玩过吗? 玩了多少局? 胜率还可以吗?

**Comment by ycdoit** [comment]
这个python的https://github.com/MahjongRepository/tenhou-python-bot/issues/3 只可以选择discard哪个牌, 不能做出meld的选择. 不过文档里倒是说可以正常的玩几百盘了.

**Comment by zhangjk95** [comment]
这只是一个客户端，用户（或者程序）可以通过标准输入输出来查看当前的状态并控制打哪张牌，并没有AI。AI在另一个repo里，打了几十场发现胜率一般。

**Comment by zhangjk95** [comment]
看了下那个python版本的胜率，和这个好像差不多，可能这个和了率更高一些。

**Comment by ycdoit** [comment]
这个repo可以选择要不要chow,pong,kong吗？ 如果我想添加这些功能（让他更完整一些），有实践方面的建议吗？比如想看tenhou发过来的message是用web的版本吗？ 收发的网络包你用什么工具查看？

**Comment by zhangjk95** [comment]
这个是日本麻将，一番起和的，如果门清的话至少可以保证有立直一番，而如果鸣牌的话就必须要有别的役种保证至少有一番可以和，就比较麻烦，要判断的东西多很多。用的是flash版本，抓包用wireshark，另外用了flash反编译器把flash的actionscript代码反编译了出来用作参考。

**Comment by ycdoit** [comment]
谢谢!

**Comment by ycdoit** [comment]
可以加一下微信吗, 以后有问题可以交流 一下? 我的微信号是 ycdoit
