### ISSUE TITLE
An issue after logging in.

### ISSUE THREAD

**Issue by Ricanry** [zhangjk95/Tenhou-Client#2]
Hi ZhangJK!
I've met an issue when I tried to run Tenhou-Client in my vps, based on Centos 7 with latest Docker-CE. It runs well until the program logging in tenhou.net with an ID or just "NoName", but it seems failed to reserve a match. 
When I run it in Docker it just shows "login" but nothing else, and tenhou.net will tell that the player has already online. (このﾌﾟﾚｰﾔは既に接続済みです)
 The only way to figure it out is logging in tenhou.net and play a match myself, then running the Client, which turns out the Client could play mahjong but just cannot reserve one.
I don't know whether it's a bug or something wrong with my settings lol.
BTW, how could you play "High" ranking without buying an "有料版"?

**Comment by zhangjk95** [comment]
Not sure whether I got your point.

It seems that you can successfully log in with this client, but cannot start a game after logging in.
Make sure `GameType_Mode` and `GameType_Match` are in a common combination. Common combinations are: `{GameType_Mode: Normal, GameType_Match: EastSouth}`(東南喰赤) and `{GameType_Mode: Fast, GameType_Match: East}`(東喰赤速). Although you can try other combinations, it is hard to find other players to play with you.

Besides, make sure you have set `Lobby` to 0 if you are not playing in a private lobby.

If the problem still occurs, you may edit the `Dockerfile` and replace line 2 with
    CMD ["sh", "-c", "mono ./Tenhou.exe"] # remove the grep filter
Then you can see more detailed information and see what's going on.

**Comment by zhangjk95** [comment]
Playing in a high ranking game is not prohibited by the Tenhou backend. You just cannot click the button to reserve a game if you are using a flash client or a web client :)

**Comment by Ricanry** [comment]
app.config的设置应该是没有问题的，因为即使使用初始设置（NoName+般南）也是会卡在login的界面……
我按照你说的更改了`dockerfile`，打开client后返回了如下数据.
```
[root@host Tenhou-Client]# docker run -it tenhou-client
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <HELO name="ID431D3AB2-HTWn8DMZ" tid="f0" sx="M" />
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <HELO uname="%E6%9C%A8%E5%8E%9F%E3%81%BE%E3%81%95%E3%82%80%E3%81%AD" auth="20180305-8b552b61" PF4="7,0,1499.48,18.0,9,7,11,8,0,255,58,31,54,69" ratingscale="PF3=1.000000&PF4=1.000000&PF01C=0.582222&PF02C=0.501632&PF03C=0.414869&PF11C=0.823386&PF12C=0.709416&PF13C=0.586714&PF23C=0.378722&PF33C=0.535594&PF1C00=8.000000" rr="PF3=0,0&PF4=115983,0&PF01C=0,0&PF02C=0,0&PF03C=0,0&PF11C=0,0&PF12C=0,0&PF13C=0,0&PF23C=0,0&PF33C=0,0&PF1C00=0,0"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <AUTH val="20180305-4b159821"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <CHAT text="%2Flobby%200" />
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <JOIN t="0,9" />
Login
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <LN n="qz1pv1RS1Cz" j="C3D4C1B12D3C1D4C8C4D12B13C1B3B3B1C" g="CM1E2E1FQ3U1BI12Eo3M1Bo12CQ4g12U12P1Bg2n2e2D1e1b1J1b2J"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <CHAT lobby="0000"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <LN n="qz1pv1RS1Cz" j="C3D4C1B12D3C1D4C8C4D12B13C1B3B3B1C" g="CM1E2E1FQ3U1BI12Eo3M1Bo12CQ4g12U12P1Bg2n2e2D1e1b1J1b2J"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <LN n="qs1po1RL1Cz" j="C3D1D3C1C15C5C8C4D12B12C2B1B2C3C5B" g="CQ1E2E1FM3U1BI12Es3M1Bo12CM4g12U12P1Bd2n2e2D1e1e1J1b2J"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <LN n="qv1pq1RG1DT" j="C3D1B3C1D12C3C1D4C8D16B13B1B1B2B3B1B1C3B" g="CQ1E2E1FQ3U1BI12Es3M1Bk12CM4k12U12P1Bd2n2h2D1e1e1J1b2J"/>
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Send: <Z />
/usr/src/app/build/Tenhou.exe Information : 0 : Receive: <LN n="rA1pw1RL1DN" j="3D1C3C1D15C1C4C8D4B12B13B1B1B2B3C1C1C3B" g="CU1E2E1FQ3U1BI12Eo3M1Bo12CM4k12U12S1Bd2n2h2D1e1Y1J1b2J"/>
Client closed.
```
如果不Ctrl+C挂起的话会一直重复2次`Send: <Z />`和一次`Receive: <LN n="blahblah`……
但是自己先开一局，再打开Client的话还是可以显示reinit E1 blahblah……

还有几个细节可以供你参考：
（1）我周六的时候是可以正常运行的，但是我vps宕机了一下，重装系统后按照老样子安装docker等工具后，就重复卡在login上了，
（2）正常使用时，用vim修改app.config时会提示该文件已经被占用，需要强制修改并用`:wq!`指令才能保存，而现在则可以直接修改保存.

我今天才发现你是复旦的学长啊23333. 我是15级数院的，你已经毕业了吗？

**Comment by zhangjk95** [comment]
之前能用而现在不能用的话有可能是被天凤封IP了。IP被封的话确实就体现为你遇到的这种情况。但是一般不太会有封IP这种事情发生，除非你频繁地掉线或发送不正确的数据，会被天凤暂时封一段时间，你可以换一个IP尝试。

我是13级计算机学院的，目前已经毕业。

**Comment by Ricanry** [comment]
确实可能发生了频繁掉线的情况，我等下换个vps试试好了. 
周六尝试的时候我设置的速东，好像数据比较惨淡（1+6+5+9好像？），不知道是不是聚类错觉(笑). 我自己是速东升特的，和麻将社的人交流起来策略上确实不太相同.
总之谢谢啦！膜一下dalao

**Comment by zhangjk95** [comment]
不建议用这个AI打速东，每一步的时间不够完成决策，容易导致超时而被系统踢掉，如果频繁超时也可能会封IP
